services:
  app:
    image: pocketgod/express-app:latest
    container_name: my-express-app
    ports:
      - "8080:8080"
    restart: always
    # Метка для Watchtower (опционально, если не указано, он следит за всеми)
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup
    restart: always
